name: Auto approve
on: pull_request_target


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: 
    steps:
      - uses: actions/labeler@v5
      - uses: hmarr/auto-approve-action@v4
        with: 
          review-message: "Auto approved for merging during UWB-CSS-BOOTUP"
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          